syntax = "proto3";

package broker;

option go_package = "./proto";

message PingRequest {
    string worker_id = 1;
}

message PingResponse {
    string message = 1;
}

message StreamRequest {
    string worker_id = 1;
}

message StreamMessage {
    Task task = 1;
}

service BrokerService {
    rpc Ping(PingRequest)
        returns (PingResponse);

    rpc StreamTasks(StreamRequest)
        returns (stream StreamMessage);

    rpc SubmitTask(SubmitTaskRequest)
        returns (SubmitTaskResponse);

    rpc PollTask(PollTaskRequest)
        returns (PollTaskResponse);

    rpc AckTask(AckTaskRequest)
        returns (AckTaskResponse);

    rpc Heartbeat(HeartbeatRequest)
        returns (HeartbeatResponse);
}

message Task{
    int64 id = 1;
    string payload = 2;
}

message SubmitTaskRequest{
    int64 id = 1;
    string payload = 2;
}

message SubmitTaskResponse{
    bool success = 1;
}

message PollTaskRequest{
    string worker_id = 1;
}

message PollTaskResponse {
    Task task = 1;
    bool found = 2;
}

message AckTaskRequest {
    int64 task_id = 1;
    string worker_id = 2;
}

message AckTaskResponse {
    bool success = 1;
}

message HeartbeatRequest {
    string worker_id = 1;
}

message HeartbeatResponse {
    bool success = 1;
}